# Generated by Django 3.2.13 on 2023-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_reasonforerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_1_mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_2_mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
